FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements_mlflow.txt .

RUN pip install --no-cache-dir -r requirements_mlflow.txt

# Création du répertoire de travail pour le script
RUN mkdir -p /app/ml && chown -R 1000:0 /app/ml
COPY ml/ ./ml/

EXPOSE 5000